# Generated by Django 6.1.1 on 2026-09-16 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('idCat', models.AutoField(primary_key=True, serialize=False)),
                ('nomCat', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('refProd', models.AutoField(primary_key=True, serialize=False)),
                ('intituleProd', models.CharField(max_length=200)),
                ('prixUnitaireProd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produit_categorie', to='monApp.categorie')),
            ],
        ),
    ]
