# Generated by Django 6.1.1 on 2026-09-17 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rayon',
            fields=[
                ('idRayon', models.AutoField(primary_key=True, serialize=False)),
                ('nomRayon', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Contenir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('produits', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produit', to='monApp.produit')),
                ('rayons', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rayons', to='monApp.rayon')),
            ],
            options={
                'unique_together': {('produits', 'rayons')},
            },
        ),
    ]
