# Generated by Django 6.1.1 on 2026-09-17 08:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0002_rayon_contenir'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='dateFabrication',
            field=models.DateField(default=datetime.date(2026, 9, 17)),
        ),
    ]
