# Generated by Django 6.1.1 on 2026-09-17 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0003_produit_datefabrication'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statut',
            fields=[
                ('idStatus', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=200)),
            ],
        ),
    ]
