# Generated by Django 6.1.1 on 2026-10-07 13:29

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0005_produit_statut'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statut',
            old_name='idStatus',
            new_name='idStatut',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='dateFabrication',
        ),
        migrations.RemoveField(
            model_name='statut',
            name='libelle',
        ),
        migrations.AddField(
            model_name='produit',
            name='dateFabProd',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='statut',
            name='libelleStatut',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produit',
            name='statut',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produit_statut', to='monApp.statut'),
        ),
        migrations.DeleteModel(
            name='Contenir',
        ),
    ]
