# Generated by Django 6.1.1 on 2026-10-07 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0006_rename_idstatus_statut_idstatut_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contenir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qte', models.PositiveIntegerField()),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenir_produit', to='monApp.produit')),
                ('rayon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenir_rayon', to='monApp.rayon')),
            ],
        ),
        migrations.AddField(
            model_name='produit',
            name='rayons',
            field=models.ManyToManyField(related_name='produits', through='monApp.Contenir', to='monApp.rayon'),
        ),
    ]
