# Generated by Django 6.1.1 on 2026-10-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0007_contenir_produit_rayons'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='contenir',
            constraint=models.UniqueConstraint(fields=('produit', 'rayon'), name='unique_produit_rayon'),
        ),
    ]
